disabled-worlds:
  - example_world
  - another_world

biomes:
  # if u use PlaceholderAPI Plugin you can display a image,custom font Ex:
  #PLAINS:
  #  message: "&aEntering the sunny plains! %image_placeholder%" <- PlaceholderAPI image
  #  display: "title"

  # display option
  # - title (the message will appear as title)
  # - actionbar (the message will appear as action bar)
  # Vanilla Biomes
  PLAINS:
    message: "&aEntering the sunny plains!"
    display: "title"
  DESERT:
    message: "&eEntering the hot desert!"
    display: "title"
  FOREST:
    message: "&2Entering the lush forest!"
    display: "title"
  NETHER_WASTES:
    message: "&cEntering the fiery Nether Wastes!"
    display: "title"
  SOUL_SAND_VALLEY:
    message: "&7Entering the eerie Soul Sand Valley!"
    display: "title"
  CRIMSON_FOREST:
    message: "&4Entering the Crimson Forest!"
    display: "title"
  WARPED_FOREST:
    message: "&9Entering the Warped Forest!"
    display: "title"
  BASALT_DELTAS:
    message: "&8Entering the Basalt Deltas!"
    display: "title"
  THE_END:
    message: "&5Entering The End!"
    display: "title"
  END_HIGHLANDS:
    message: "&dEntering the End Highlands!"
    display: "title"
  END_MIDLANDS:
    message: "&dEntering the End Midlands!"
    display: "title"
  SMALL_END_ISLANDS:
    message: "&dEntering the Small End Islands!"
    display: "title"
  END_BARRENS:
    message: "&dEntering the End Barrens!"
    display: "title"