name: BiomesTitle
version: 1.4
main: me.supramental.biomestitle.BiomesTitle
api-version: '1.21'
description: Add titles to biome
author: supramental
softdepend:
  - PlaceholderAPI
commands:
  btwand:
      description: Gives the player a BiomeTitle wand.
      usage: /btwand
  btsetarea:
    description: Sets a custom area with a message.
    usage: /btsetarea <name> <message> <title or actionbar>

permissions:
  biomestitle.command.wand:
    description: Allows the player to receive a BiomeTitle wand.
    default: op
  biomestitle.command.setarea:
    description: Allows the player to set custom areas.
    default: op
